name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-22.04
    # env: 
      # PATH: $PATH:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
    #     PATH: $HOME/.local/bin:$PATH
    #     LD_LIBRARY_PATH: $HOME/.local/lib/x86_64-unknown-linux-gnu/:$HOME/.local/lib:$LD_LIBRARY_PATH
    #     PKG_CONFIG_PATH: $HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH
    #     C_INCLUDE_PATH: $HOME/.local/include:$C_INCLUDE_PATH
    #     CPLUS_INCLUDE_PATH: $HOME/.local/include:$CPLUS_INCLUDE_PATH
    steps:
    - run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 15 all
        sudo apt install tar meson clang libgtest-dev libbenchmark-dev ninja-build pkg-config cmake
        sudo apt-get install g++20 gcc-12
        sudo apt-get install --reinstall binutils
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - run: echo $GITHUB_PATH
    - run: gcc --version
    - run: llvm-config --version
    - run: |
        meson setup builddir
        cd builddir
        meson test
