name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-22.04
    # env: 
      # PATH: $PATH:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
    #     PATH: $HOME/.local/bin:$PATH
    #     LD_LIBRARY_PATH: $HOME/.local/lib/x86_64-unknown-linux-gnu/:$HOME/.local/lib:$LD_LIBRARY_PATH
    #     PKG_CONFIG_PATH: $HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH
    #     C_INCLUDE_PATH: $HOME/.local/include:$C_INCLUDE_PATH
    #     CPLUS_INCLUDE_PATH: $HOME/.local/include:$CPLUS_INCLUDE_PATH
    steps:
    - run: |
        sudo apt install tar meson clang llvm-dev libgtest-dev libbenchmark-dev ninja-build pkg-config cmake
        printenv
        echo $PATH
        llvm-mca --version
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - run: echo $GITHUB_PATH
    - run: gcc --version
    - run: |
        CC_LD=lld CXX_LD=lld CXXFLAGS="" meson setup builddir -Db_santize=address -Db_coverage=true
        cd builddir
        meson test
