name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: sudo apt install meson gcc clang llvm-dev libgtest-dev libbenchmark-dev ninja-build pkg-config cmake
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
